# Data Visualization (2018/19)

## Solutions for Assignment 2 - Exploratory Data Analysis

Presented by Group 32: 
- Kamolchanok Tangsri
- Alfitra Rahman

Date: 22.11.2018, 22:00

Hints: 
- Double click on a cell to edit it.
- Enter the Markdown mode in the drop-down menu above (it may say Code for new cells).
- Run a cell by pressing CTRL+Enter
- Markdown docu: http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html
- Markdown cheatsheet: http://datascience.ibm.com/blog/markdown-for-jupyter-notebooks-cheatsheet/

### Exercise 1: Choose a data set

We will use the Python Data Analysis Library (Pandas) to work with the data. Pandas provides a rich feature set for working with tabular data including data structures and analysis tools.

A 10 minute introduction to pandas with all neccessary functions can be found here: http://pandas.pydata.org/pandas-docs/stable/10min.html (Quickly skim over the available functionality. You don't have to learn it yet.)

In [2]:
# import the pandas library and call it pd for further usage
import pandas as pd

#### Sample code to load the baseball data and get basic statistics

In [3]:
# read the csv file into a pandas dataframe and print the first lines of the table
filename = "baseball_data.csv"
df = pd.read_csv( filename, header=0 )
df.head()

name handedness  height  weight    avg   HR
0       Tom Brown          R      73     170  0.000    0
1  Denny Lemaster          R      73     182  0.130    4
2       Joe Nolan          L      71     175  0.263   27
3     Denny Doyle          L      69     175  0.250   16
4   Jose Cardenal          R      70     150  0.275  138

In [4]:
df.describe(include="all")

name handedness       height       weight          avg  \
count         1157       1157  1157.000000  1157.000000  1157.000000   
unique        1151          3          NaN          NaN          NaN   
top     Jim Wright          R          NaN          NaN          NaN   
freq             2        737          NaN          NaN          NaN   
mean           NaN        NaN    72.756266   184.513397     0.186793   
std            NaN        NaN     2.142272    15.445995     0.106175   
min            NaN        NaN    65.000000   140.000000     0.000000   
25%            NaN        NaN    71.000000   175.000000     0.138000   
50%            NaN        NaN    73.000000   185.000000     0.238000   
75%            NaN        NaN    74.000000   195.000000     0.258000   
max            NaN        NaN    80.000000   245.000000     0.328000   

                 HR  
count   1157.000000  
unique          NaN  
top             NaN  
freq            NaN  
mean      45.359551  
std       74.065110  
min        0.000000  
25%        1.000000  
50%       15.000000  
75%       55.000000  
max      563.000000

#### Sample code to load the Titanic data and get basic statistics

In [5]:
# read the csv file into a pandas dataframe and print the first lines of the table
filename = "titanic3.csv"
df = pd.read_csv( filename, header=0 )
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

     age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.00      0      0   24160  211.3375       B5        S    2    NaN   
1   0.92      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.00      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [6]:
df.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [7]:
df.describe(include="all")

pclass     survived              name   sex          age  \
count   1309.000000  1309.000000              1309  1309  1046.000000   
unique          NaN          NaN              1307     2          NaN   
top             NaN          NaN  Kelly, Mr. James  male          NaN   
freq            NaN          NaN                 2   843          NaN   
mean       2.294882     0.381971               NaN   NaN    29.881138   
std        0.837836     0.486055               NaN   NaN    14.413493   
min        1.000000     0.000000               NaN   NaN     0.170000   
25%        2.000000     0.000000               NaN   NaN    21.000000   
50%        3.000000     0.000000               NaN   NaN    28.000000   
75%        3.000000     1.000000               NaN   NaN    39.000000   
max        3.000000     1.000000               NaN   NaN    80.000000   

              sibsp        parch    ticket         fare        cabin embarked  \
count   1309.000000  1309.000000      1309  1308.000000          295     1307   
unique          NaN          NaN       929          NaN          186        3   
top             NaN          NaN  CA. 2343          NaN  C23 C25 C27        S   
freq            NaN          NaN        11          NaN            6      914   
mean       0.498854     0.385027       NaN    33.295479          NaN      NaN   
std        1.041658     0.865560       NaN    51.758668          NaN      NaN   
min        0.000000     0.000000       NaN     0.000000          NaN      NaN   
25%        0.000000     0.000000       NaN     7.895800          NaN      NaN   
50%        0.000000     0.000000       NaN    14.454200          NaN      NaN   
75%        1.000000     0.000000       NaN    31.275000          NaN      NaN   
max        8.000000     9.000000       NaN   512.329200          NaN      NaN   

       boat        body     home.dest  
count   486  121.000000           745  
unique   27         NaN           369  
top      13         NaN  New York, NY  
freq     39         NaN            64  
mean    NaN  160.809917           NaN  
std     NaN   97.696922           NaN  
min     NaN    1.000000           NaN  
25%     NaN   72.000000           NaN  
50%     NaN  155.000000           NaN  
75%     NaN  256.000000           NaN  
max     NaN  328.000000           NaN

#### Your selection:
Selected dataset: Baseball data

### Exercise 2: Data queries

1. What is the majority of handedness among baseball players?
2. What is the average of the batting averages by handedness?
3. What is the most suceessful handedness of basball player deciding from the average batting and the number of home runs?
4. How does the height of a baseball player affect his batting average?
5. Does the batting average correlate to the number of home runs?
6. Who are the top ten best baseball players judging from the average batting and the number of home runs?

### Exercise 3: Data analysis

Here is sample code to pass your data from the pandas data frame to bokeh and render a graphic inside the notebook.

In [8]:
filename = "baseball_data.csv"
df = pd.read_csv( filename, header=0 )

In [9]:
# compute a histogram of the height variable
df_height = df['height'].value_counts().to_frame('count')
df_height.head()

count
72    232
73    194
74    180
71    145
75    121

In [10]:
# import bokeh 
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource

# tell bokeh to show the figures in the notebook
from bokeh.io import output_notebook
output_notebook()

Loading BokehJS ...

##  Q1: What is the majority of  handedness among baseball players?

We apply a pie chart to represent this data. The handedness values are identified as left, right and both. The count value is calculated from the data. Then we generate a pie chart from this count. 

In [11]:
#Q1: What is the dominant handedness of baseball players?

# compute a histogram of the handedness variable
df_handedness = df['handedness'].value_counts().reset_index()
# set column names
df_handedness.columns = ['handedness', 'count']
df_handedness.head()

handedness  count
0          R    737
1          L    316
2          B    104

In [12]:
#Q1: Contd.

# display pie chart of handedness
import matplotlib.pyplot as plt

#For labels
handedness_labels = ['Right','Left','Both']

plt.figure(figsize=(4, 4))

colors = ['#2171b5','#4292c6','#c6dbef']

#draw pie chart
plt.pie(df_handedness['count'], labels=handedness_labels, colors=colors,
        autopct='%1.1f%%', startangle=90)
plt.title('Handedness count of baseball players', y=1.1)
plt.axis('equal')
plt.show()

<Figure size 400x400 with 1 Axes>

As we can notice from the pie chart that the majority of handedness is Right at 63.7%. The number of right handed players are more than double time of left handed players. Players who both hands are identical also significant at 9%.

##  Q2: What is the average of the batting averages by handedness?
A bar chart represent the mean of batting averages grouped by handedness.

In [13]:
#Q2: What is the average of the batting averages by handedness?
import numpy as np
from bokeh.io import show
from bokeh.plotting import figure

# x-axis: handedness
handedness = ['Both','Left','Right']

# y-axis: avg - mean of average batting
mean_avg = df.groupby('handedness').mean()['avg']

colors = ['#c6dbef','#4292c6','#2171b5']
q2 = figure(x_range=handedness, y_range=(0,0.23), plot_width = 400, plot_height=300, 
            x_axis_label= "Handedness", y_axis_label="Average batting",
            title="Average of Batting Average")
q2.vbar(x=handedness, top=mean_avg, width=0.4, color=colors)

# to make the x-grid invisible
q2.xgrid.grid_line_color = None

show(q2)

This bar chart displays the mean of batting average grouped by handedness. According to the chart,the mean of batting average among of left-handed and both-handed players is almost similar. However, the mean of the right-handed players is slightly lower than the other two groups although they are the majority of baseball players in this study (based on the finding in Q1.)

## Q3.What is the most suceessful handedness of basball player deciding from the average batting and the number of home runs?

In [14]:
#Q2: What is the average of home runs by handedness?
import numpy as np
from bokeh.core.properties import value
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import LinearAxis,Range1d
from bokeh.transform import dodge


# x-axis: handedness
handedness = ['Both','Left','Right']

# y-axis: avg - mean of average batting
mean_avg = df.groupby('handedness').mean()['avg']

# y-axis-Right: avg - mean of average batting
mean_hr = df.groupby('handedness').mean()['HR']
data = {'handedness' : handedness,
        'HR'   : mean_hr,
        'avg'   : mean_avg}
source = ColumnDataSource(data=data)
colors = ['#c6dbef']
colors_avgbat = ['#e5f5f9']
q2 = figure(x_range=handedness, plot_width = 500, plot_height=300, y_range = Range1d(start=0, end=60),
            x_axis_label= "Handedness", y_axis_label="Average number of Home Runs",
            title="Average number of Home Runs and average batting",)
q2.vbar(x=dodge('handedness', -0.25, range=q2.x_range), top='HR', width=0.2, source=source,
       color="#c9d9d3", legend=value("HR"))

q2.vbar(x=dodge('handedness',  0.0,  range=q2.x_range), top='avg', width=0.2, source=source,
       color="#718dbf", legend=value("avg"),y_range_name='Average of Batting Average')
q2.extra_y_ranges = {"Average of Batting Average": Range1d(start=0, end=0.23)}
q2.add_layout(LinearAxis(y_range_name="Average of Batting Average",axis_label='Average of Batting Average'), 'right' )

# to make the x-grid invisible
q2.xgrid.grid_line_color = None

show(q2)

As we can see from the bar chart, it is very obvious that left-handed players is the most successful because both means of home run and average batting are the highest. Then following by right-handed players, even if the mean of batting average is lower than the both-handed player. However, the mean of home run is higher

## Q4.How does the height of a baseball player affect his batting average?

For this query we will look at the heights of the players and their respective batting averages by drawing a scatter plot. We try to see how the height of players affect the performance indicated by their batting averages. Additionally we will identify the height of the player with the highest batting average. 

In [15]:
#Q4: Does the batting average correlate to Height?
from bokeh.models import BoxAnnotation, Span

#x-axis: height of players
df_heights = df['height']

#y-axis: batting averages
df_batting_avg = df['avg']

q4 = figure(plot_width=650, plot_height=400, x_axis_label= "Player heights (inches)", y_axis_label="Batting average",
           title="Batting average distribution with player heights")

# circles for the distribution
q4.circle(df_heights, df_batting_avg, size=6, color="navy", alpha=0.5)
q4.xaxis[0].ticker.desired_num_ticks = 15

#highest batting average
highest_avg = df['avg'].max()
q4.circle(72, highest_avg, size=6, color="red")

#hightlight the best batting averages 
best_box = BoxAnnotation(plot=q4, bottom=0.3, left=69, right=75, fill_alpha=0.25, fill_color='yellow')

#line for height mean
vline = Span(location=72.756266, dimension='height', line_color='red', line_width=1)

q4.renderers.extend([best_box, vline])

# show the results
show(q4)

With this scatter plot of the batting averages with the player heights, we can see that the batting averages are high (more than 0.3) for the height range between 69 and 75 inches (highlighted in yellow area). The player with highest batting average has a height of 72 inches (shown as a red dot). If we consider the mean of heights, 72.756266, players with heights close to this mean usually have high batting averages.
In the next bar chart we look at how the batting average mean is distributed with the player heights.

In [16]:
# Q4: Contd.

#average batting averages grouped by height
mean_avg_by_height = df.groupby('height').mean()['avg']
df_height_meanavg = mean_avg_by_height.reset_index()

q4 = figure(x_range=(64, 81), y_range=(0,0.3), plot_width = 600, plot_height=400, 
            x_axis_label= "Player heights", y_axis_label="Mean Batting average",
            title="Average of Batting Average over height")
q4.vbar(x=df_height_meanavg['height'], top=mean_avg_by_height, width=0.4)

#increase x axis ticks
q4.xaxis[0].ticker.desired_num_ticks = 15

show(q4)

This chart is left skewed indicating that the mean of batting average is higher for shorter players. Specifically, the player height 67 has a mean batting average of 0.263250. And there is a decline of batting averages with the increase of height.
However, This can be attributed to the fact of having a smaller number of short players. Nonetheless, even those amount of players have managed to get a high batting average among themselves. Even in the scatter plot we see that the players shorter than 69 have managed to keep a non-zero batting average.

## Q5.Does the batting average correlate to the number of home runs?
In order to identify the correlation between batting average and the number of home runs. We decided to use a scatter plot.

In [18]:
#Q5: Does the batting average correlate to the number of home runs?
from bokeh.models import LinearAxis, Range1d

# x-axis: avg - batting average
df_avg = df['avg']

# y-axis: HR - number of home runs
df_hr = df['HR']

q5 = figure(plot_width=800, plot_height=600, x_axis_label= "Batting average", y_axis_label="# Home runs",
           title="Relationship between batting average and the number of home runs")

# add a circle renderer with a size, color, and alpha
q5.circle(df_avg, df_hr, size=5, color="navy", alpha=0.3)

#hightlight the best batting averages 
best_box = BoxAnnotation(plot=q5, bottom=200, left=0.2, right= 0.31, fill_alpha=0.25, fill_color='yellow')
q5.renderers.extend([best_box])

# show the results
show(q5)

From the scatter plot, we can see that most baseball players have batting average between 0.21 and 0.28. (The mean of batting average is 0.19.) However, we do not see any correlation between batting average and the number of home runs. It is noticeable that most players who have larger number of home runs (more than 200) are usually have batting average between 0.25 and 0.3 which is higher than the mean of batting average.
Although batting average is a performance indicator, it does not determine the number of home runs. In other words, it cannot be concluded that the players who have higher batting average will always have higher change of hitting a home run.

## Q6.Who are the top ten best baseball players judging from the average batting and the number of home runs?
Firstly,We looked at the top 5 players sorting by batting average with descending order. Their number of Homeruns are also displayed.

In [22]:
#Q6: Who are the top 10 baseball players considering batting average and number of Homeruns?

#top 10 by batting average
sorted_avg = df.sort_values(by='avg', ascending=False)
top_10_avg = sorted_avg.loc[:,['name', 'avg', 'HR']][0:5]
top_10_avg

name    avg   HR
281      Rod Carew  0.328   92
861  Lyman Bostock  0.311   23
547     Matty Alou  0.307   31
934     Ralph Garr  0.306   75
792   Bill Madlock  0.305  163

Then we visualize the top 5 players sorting by number of homeruns with descending order. Their batting average is also on display.

In [23]:
#top 10 by number of Homeruns
sorted_hr = df.sort_values(by='HR', ascending=False)
top_10_hr = sorted_hr.loc[:,['name', 'HR', 'avg']][0:5]
top_10_hr

name   HR    avg
656    Reggie Jackson  563  0.262
995      Mike Schmidt  548  0.267
972   Willie Stargell  475  0.282
422  Carl Yastrzemski  452  0.285
45       Dave Kingman  442  0.236

Next we want to see any correlation between the top 5 players by batting average and by the number of home runs by a scatter plot. From the above tables we already see that these dimensions are completely disjoint. We would like to show with scatter plot. For this we focus on the batting averages above 0.23, because the lowest batting average for top number of homeruns is 0.236. Then we mark the top 5 batting averages and the top 10 number of homeruns to find any intersection between the both of them, we will mark the areas in the chart corresponding with the top 5 values of both dimensions.

In [24]:
from bokeh.models import Legend, Label

#batting averages above 0.23, because top home runs have lovest batting average of 0.236
df_avg_above_23 = df.loc[df['avg'] > 0.23]

q6 = figure(plot_width=900, plot_height=500, x_axis_label= "Batting average", y_axis_label="# Home runs",
           title="Above 0.23 batting average with number of home runs")

# add a circle renderer with a size, color, and alpha
q6.circle(df_avg_above_23['avg'], df_avg_above_23['HR'], size=5, color="navy", alpha=0.2)

# add circles for the top 10 number of homeruns
c1 = q6.circle(top_10_hr['avg'], top_10_hr['HR'], size=5, color="maroon", alpha=0.8)

#add circles for the top 10 batting average
c2 = q6.circle(top_10_avg['avg'], top_10_avg['HR'], size=5, color="green", alpha=0.8)

q6.xaxis[0].ticker.desired_num_ticks = 20

legend = Legend(items=[
    ("Top 10 # of homeruns",   [c1]),
    ("Top 10 batting averages", [c2])
], location=(0, 200))



#hightlight the best batting averages 
best_avg_box = BoxAnnotation(plot=q6, left=0.299, fill_alpha=0.15, fill_color='yellow')
#highlight best homeruns
best_hr_box = BoxAnnotation(plot=q6, bottom = 379, fill_alpha=0.15, fill_color='green')
q6.renderers.extend([best_avg_box, best_hr_box])

label = Label(x=0.298, y=382, text='Jim Rice')
q6.add_layout(label)
q6.add_layout(legend, 'left')

# show the results
show(q6)

From this chart we see that the top 5 batting averages and top 5 number of homeruns are disjoint. There is no correlation with both values.The intersection area does not contain any value. So it is difficult to determine the overall top 5 players with respecto to both the batting average and the number of homeruns.

### Exercise 4: Write a summary
Write a one paragraph summary about what you found out about your dataset, your difficulties and how you would continue the exploration.

According to baseball dataset, There are multivariate data. It is quite difficult to find the hidden information in the data. For example, in question 6, It is difficult to decide the overall top 5 players according to disjoint between batting averages and number of homeruns. For the improvment of our work in question 6, If we change the from top 5 players to top 10 players, will found the one player, Jim Rice who are successful player by determining  batting averages and number of homeruns.